export const allFeedbacks = [
  "AÚN SIN RESPUESTAS",
  "NO SE MATRICULARÁ",
  "INCONTACTABLE",
  "PERSONA INTERESADA QUE ENVIARÁ DOCUMENTACIÓN",
  "PERSONA QUE ENVIÓ DOCUMENTACIÓN PERO LE FALTA FIRMAR SU MATRÍCULA",
  "PERSONA QUE IRÁ A MATRICULARSE DIRECTAMENTE A LA ESCUELA",
  "PERSONA CON DOCUMENTACIÓN Y MATRÍCULA FIRMADA EN ESCUELA",
  "INTERESADA PARA PRÓXIMO AÑO",
  "PERSONA QUE ENVÍA DOCUMENTACIÓN Y SE DEBE TRASLADAR A OTRA PLANILLA",
];

export const GENDER_OPTIONS = ["", "MASCULINO", "FEMENINO", "OTROS"];
export const SOURCE_OPTIONS = ["", "REDES SOCIALES", "CAPTADOR"];
export const SCHOOL_OPTIONS = [
  "",
  "QUINTA NORMAL",
  "BUÍN",
  "LA GRANJA",
  "ÑUÑOA",
  "PUDAHUEL",
  "SAN MIGUEL",
];
export const COURSE_OPTIONS = [
  "",
  "1° NIVEL BÁSICO",
  "2° NIVEL BÁSICO",
  "3° NIVEL BÁSICO",
  "1° NIVEL MEDIO",
  "2° NIVEL MEDIO",
];
export const CONTACT_PERSON_OPTIONS = [
  "",
  "LORENA",
  "ARLETTE",
  "MARÍA",
  "ROWINA",
];
export const COMMUNICATION_PREFERENCE_OPTIONS = ["", "WHATSAPP", "TELÉFONO"];
export const CALL_STATUS_OPTIONS = ["", "SÍ", "NO"];

export const DROPDOWN_ITEM_HEIGHT_PX = 60;

export const CAPTATOR_NAMES = [
  "Lorena",
  "Arlette",
  "María",
  "Rowina",
  "No Ingresa Captador",
];

const Constants = {
  allFeedbacks,
  GENDER_OPTIONS,
  SOURCE_OPTIONS,
  SCHOOL_OPTIONS,
  COURSE_OPTIONS,
  CONTACT_PERSON_OPTIONS,
  COMMUNICATION_PREFERENCE_OPTIONS,
  CALL_STATUS_OPTIONS,
  DROPDOWN_ITEM_HEIGHT_PX,
  CAPTATOR_NAMES,
};

export default Constants;
